spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/managerDb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    initialize: true
    data: classpath:data.sql
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
